### ISSUE TITLE
Error in downloading DB

### ISSUE THREAD

**Issue by YonghuiDong** [joannawolthuis/MetaDBparse#3]
Hi @joannawolthuis ,

I am unable to download HMDB. Every time when I run `build.HMDB`, I got the following error:

    Error in utils::download.file(file.url, zip.file, mode = "wb", cacheOK = TRUE,  : 
      download from 'http://www.hmdb.ca/system/downloads/current/hmdb_metabolites.zip' failed
    In addition: Warning messages:
    1: In utils::download.file(file.url, zip.file, mode = "wb", cacheOK = TRUE,  :
      downloaded length 337985337 != reported length 626407029
    2: In utils::download.file(file.url, zip.file, mode = "wb", cacheOK = TRUE,  :
       URL 'https://hmdb.ca/system/downloads/current/hmdb_metabolites.zip': Timeout of 60 seconds was reached

Same error was also observed for `build.FoodDB`.

Could you please help? Is there an option to allow the user to download the DB by themselves?

Thanks a lot.

Dong

**Comment by joannawolthuis** [comment]
Hi there! Seems there is a timeout for downloads that I only am learning of now.
At the beginning of your R session, can you try setting:
`options(timeout=600)` 
that should give it 10 minutes at least, or set it to longer as needed. If that works I'll build it in if CRAN allows it :)

**Comment by YonghuiDong** [comment]
@joannawolthuis,

Thanks a lot for your help. It works now.

Dong
