### ISSUE TITLE
Error when building KEGG DB

### ISSUE THREAD

**Issue by YonghuiDong** [joannawolthuis/MetaDBparse#4]
Hi @joannawolthuis, I got the following error when building KEGG DB.

    Error in data.table::rbindlist(lapply(kegg.cpd.list, function(x) x$path)) : 
      Item 24 has 1 columns, inconsistent with item 1 which has 3 columns. To fill missing columns use fill=TRUE.

Thanks for your help.

Yonghui Dong

**Comment by joannawolthuis** [comment]
Hi Yonghui! Thanks for your message. I'll take a look and see what's going on! :)

**Comment by YonghuiDong** [comment]
Hi @joannawolthuis

It works nicely now! 

Thanks a lot!

Yonghui Dong
